# positive_affirmations.py
# Description: A list of positive affirmations to help boost your confidence and self-esteem.

positive_affirmations = [
    "You have a remarkable sense of curiosity!",
    "You are thoughtful and considerate!",
    "Your passion for learning is inspiring!",
    "You are resilient and strong!",
    "Your determination is impressive!",
    "You have a knack for problem-solving!",
    "You are full of creative ideas!",
    "Your enthusiasm is contagious!",
    "You have a unique way of looking at the world!",
    "Your perseverance is admirable!",
    "You are a continuous learner!",
    "You handle challenges with grace!",
    "You make meaningful contributions!",
    "You have a strong sense of integrity!",
    "Your positivity brightens up the day!",
    "You approach life with courage!",
    "You have a great sense of humor!",
    "You are open-minded and welcoming!",
    "You show great empathy and understanding!",
    "You are thoughtful and reflective!",
    "You have a wonderful sense of wonder!",
    "You are an independent thinker!",
    "You are dedicated to your goals!",
    "You approach problems with a cool head!",
    "You are resourceful and clever!",
    "You embrace change with ease!",
    "You have a strong sense of justice!",
    "You bring joy to those around you!",
    "You are a great communicator!",
    "You are wise beyond your years!",
    "You have a deep sense of compassion!",
    "You are a fantastic storyteller!",
    "You inspire others with your actions!",
    "You are always looking for the good in situations!",
    "You have a calming presence!",
    "You are passionate about what you do!",
    "You are always willing to learn and grow!",
    "You are thoughtful and intentional!",
    "You have a great ability to adapt!",
    "You are an excellent listener!",
    "You have a natural talent for teaching!",
    "You are generous with your time and knowledge!",
    "You have a positive impact on the world!",
    "You are an innovative thinker!",
    "You have a strong sense of ethics!",
    "You are always striving to be better!",
    "You are curious and love exploring new ideas!",
    "You are sincere and genuine!",
    "You are thoughtful in your actions!",
    "You have a strong inner strength!"
]
